CREATE TABLE item (
  nome VARCHAR(64) NOT NULL,
  descricao VARCHAR(128) DEFAULT '',
  raridade VARCHAR(16) DEFAULT 'COMUM',
  valor_real NUMERIC NOT NULL,
  tipo VARCHAR(16) NOT NULL,

  CONTRAINT PK_ITEM PRIMARY KEY(nome),
  
  CONTRAINT CK_ITEM_VALOR CHECK valor >= 0,
  CONTRAINT CK_ITEM_TIPO CHECK(UPPER(tipo) IN ('EQUIPAMENTO', 'CONSUMIVEL'))
);

CREATE TABLE monstro (
  nome VARCHAR(64) NOT NULL,
  vida_maxima NUMERIC NOT NULL,
  pontos_poder NUMERIC NOT NULL,
  raridade VARCHAR(16) DEFAULT 'COMUM',
  habilidade VARCHAR(16) DEFAULT 'NENHUMA',
  exp_gerado NUMERIC NOT NULL,

  CONSTRAINT PK_MONSTRO PRIMARY KEY(nome),
  
  CONSTRAINT CK_MONSTRO_VIDA CHECK vida_maxima >= 0,
  CONSTRAINT CK_MONSTRO_PONTOS_PODER CHECK pontos_poder >= 0,
  CONSTRAINT CK_MONSTRO_EXP_GERADO CHECK exp_gerado >= 0,
);

CREATE TABLE masmorra (
  nome VARCHAR(64) NOT NULL,
  local VARCHAR(64),

  CONSTRAINT PK_MASMORRA PRIMARY KEY(nome),
);

CREATE TABLE missao (
  nome VARCHAR(64) NOT NULL,
  dificuldade VARCHAR(16) NOT NULL,
  exp_gerado NUMERIC NOT NULL,
  tempo_finalizar NUMERIC DEFAULT '60', -- EM SEGUNDOS
  masmorra VARCHAR(64) NOT NULL,

  CONSRAINT PK_MISSAO PRIMARY KEY(nome),
  CONSRAINT FK_MISSAO_MASMORRA FOREIGN KEY(masmorra) REFERENCES masmorra(nome),

  CONSRAINT CK_MISSAO_EXP_GERADO CHECK exp_gerado >= 0,
  CONSRAINT CK_MISSAO_TEMPOCHECK tempo >= 0,
);

CREATE TABLE espolio_monstro(
  item VARCHAR(64) NOT NULL,
  monstro VARCHAR(64) NOT NULL,
  quantidade NUMERIC NOT NULL,
  
  CONSTRAINT PK_ESPOLIO_MONSTRO PRIMARY KEY(item, monstro),
  CONSTRAINT FK_ESPOLIO_MONSTRO_ITEM FOREIGN KEY (item) REFERENCES item(nome) ON DELETE CASCADE,
  CONSTRAINT FK_ESPOLIO_MONSTRO_MONSTRO FOREIGN KEY (monstro) REFERENCES monstro(nome) ON DELETE CASCADE,

  CONSTRAINT CK_ESPOLIO_QTT CHECK quantidade >= 0,
);

CREATE TABLE monstro_masmorra (
  monstro VARCHAR(64) NOT NULL,
  masmorra VARCHAR(64) NOT NULL,
  quantidade NUMERIC NOT NULL,
  
  CONSTRAINT PK_MONSTRO_MASMORRA PRIMARY KEY (monstro, masmorra),
  CONSTRAINT FK_MONSTRO_MASMORRA_MONSTRO FOREIGN KEY (monstro) REFERENCES monstro(nome) ON DELETE CASCADE,
  CONSTRAINT FK_MONSTRO_MASMORRA_MASMORRA FOREIGN KEY (masmorra) REFERENCES masmorra(nome) ON DELETE CASCADE,

  CONSRAINT CK_MONSTRO_MASMORRA_QTT CHECK quantidade >= 0,
);

CREATE TABLE itens_gerados_missao (
  item VARCHAR(64) NOT NULL,
  missao VARCHAR(64) NOT NULL,
  quantidade NUMERIC NOT NULL,

  CONSTRAINT PK_ITENS_GERADOS_MISSAO PRIMARY KEY(item, missao),
  CONSTRAINT FK_ITENS_GERADOS_ITEM FOREIGN KEY(item) REFERENCES item(nome),
  CONSTRAINT FK_ITENS_GERADOS_MISSAO FOREIGN KEY(missao) REFERENCES missao(nome),

  CONSTRAINT CK_ITENS_GERADOS_QTT CHECK quantidade >= 0,
);

CREATE TABLE criacao_comunidade (
  missao VARCHAR(64) NOT NULL,
  comunidade VARCHAR(64) NOT NULL,
  pontuacao NUMERIC NOT NULL,

  CONSRAINT PK_CRIACAO_COMUNIDADE PRIMARY KEY(missao),
  CONSRAINT FK_CRIACAO_COMUNIDADE_MISSAO FOREIGN KEY(missao) REFERENCES missao(nome),

  CONSRAINT CK_PONTUACAO CHECK pontuacao >= 0,
);

CREATE TABLE participacao_missao (
  missao VARCHAR(64) NOT NULL,
  nacao VARCHAR(64) NOT NULL,
  cla VARCHAR(64) NOT NULL,
  data_termino TIMESTAMP NOT NULL,
  finalizaou BOOLEAN DEFAULT false,

  CONSRAINT PK_PARTICIPACAO_MISSAO PRIMARY KEY(missao, nacao, cla, data_termino),
  CONSTRAINT FK_PARTICIPACAO_NACAO_CLA FOREIGN KEY(nacao, cla) REFERENCES cla(nacao, nome),
);

CREATE TABLE consumivel (
  item VARCHAR(64) NOT NULL,
  tempo_duracao NUMERIC NOT NULL, -- segundos

  CONSRAINT PK_CONSUMIVEL PRIMARY KEY(item),
  CONSRAINT FK_CONSUMIVEL_ITEM FOREIGN KEY(item) REFERENCES item(nome),

  CONSRAINT CK_CONSUMIVEL_TEMPO CHECK tempo >= 0,
);

CREATE TABLE efeito_consumivel (
  consumivel VARCHAR(64) NOT NULL,
  nome VACHAR2(64) NOT NULL,

  CONSRAINT PK_EFEITO_CONSUMIVEL PRIMARY KEY(consumivel, nome),
  CONSRAINT FK_EFEITO_CONSUMIVEL FOREIGN KEY(consumivel) REFERENCES consumivel(item),
); 

CREATE TABLE equipamento (
  item VARCHAR(64) NOT NULL,
  nivel_permitido NUMERIC NOT NULL,
  pontos_poder NUMERIC NOT NULL,
  de_guerreiro BOOLEAN DEFAULT false,
  de_mago BOOLEAN DEFAULT false,
  de_atirador BOOLEAN DEFAULT false,
  de_curandeiro BOOLEAN DEFAULT false,

  CONSRAINT PK_EQUIPAMENTO PRIMARY KEY(item),
  CONSRAINT FK_EQUIPAMENTO_ITEM FOREIGN KEY(item), item(nome),

  CONSRAINT CK_EQUIPAMENTO_PONTOS_PODER CHECK pontos_poder >= 0,
);

CREATE TABLE habilidade_equipamento (
  equipamento VARCHAR(64) NOT NULL,
  nome VARCHAR(64) NOT NULL,

  CONSRAINT PK_HABILIDADE_EQUIPAMENTO PRIMARY KEY(equipamento, nome),
  CONSRAINT FK_HABILIDADE_EQUIPAMENTO FOREIGN KEY(equipamento) REFERENCES equipamento(item),
);
